name: Terraform

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform version
        shell: bash
        run: terraform version
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform init
        shell: bash
        run: terraform init
      - name: Terraform Plan
        shell: bash
        run: terraform plan -out=tfplan.plan
        env:
          JFROG_ACCESS_TOKEN: ${{ secrets.JFROG_ACCESS_TOKEN }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan.plan
